#!/bin/bash
# /etc/init.d/conman

### BEGIN INIT INFO
# Provides:          conman`
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
NAME=conman
DIR=/opt/conman
PROG=$DIR'/conman.py'
PIDFILE=/var/run/$NAME.pid

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        echo -n "Starting conman: "
        cd $DIR
        if [ -f $PROG ]; then
            PROG >> '/var/log/conman-shell.log' 2>&1 &
            conman_pid=$!
            echo $conman_pid > $PIDFILE
            echo 'done'
        else
            echo "thisbridge.sh file does not exist"
        exit
        fi
	;;
  stop)
	echo -n "Stopping conman: "
	start-stop-daemon --stop --signal 2 --quiet --pidfile $PIDFILE
	rm $PIDFILE
	echo "done."
	;;
  restart)
	echo "Restarting conman: "
	sh $0 stop
	sleep 5
	sh $0 start
	;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
